apiVersion: v1
kind: ConfigMap
metadata:
  name: erd-urls
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
data:
  INCIDENT_SERVICE_URL: {{ .Values.erdemo.incidentService | quote }}
  MISSION_SERVICE_URL: {{ .Values.erdemo.missionService | quote }}
