apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: findmyrelative-ui-cicd-listener
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "2"
spec:
  serviceAccountName: serviceaccount
  triggers:
  - binding:
      name: findmyrelative-ui-cicd-pipelinebinding
    template:
      name: findmyrelative-ui-cicd-triggertemplate
