# Default values for find-my-relative.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Links to Emergency Response Demo services
erdemo:
  incidentService: ""
  missionService: ""

pipelines:
  # If true, starts pipeline immediately when installed
  start: false
