{{ if .Values.frontend.token }}
apiVersion: v1
kind: Secret
metadata:
  name: findmyrelative-ui-webhook-secret
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
stringData:
  # https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line#creating-a-token
  token: {{ .Values.frontend.token }} # github auth token
  secret: {{ .Values.frontend.secret }} # add-random string data
{{ end }}
