apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: create-findmyrelative-ui-repo-webhook-run
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "7"
spec:
  taskRef:
    name: create-webhook
  inputs:
    params:
    - name: GitHubOrg
      value: {{ .Values.frontend.github.org }}
    - name: GitHubUser
      value: {{ .Values.frontend.github.user }}
    - name: GitHubRepo
      value: {{ .Values.frontend.github.repo }}
    - name: GitHubSecretName
      value: findmyrelative-ui-webhook-secret
    - name: GitHubAccessTokenKey
      value: token
    - name: GitHubSecretStringKey
      value: secret
    - name: ExternalDomain
      value: {{ .Values.frontend.github.listener | quote }}
  timeout: 1000s
  serviceAccount: serviceaccount
