apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: findmyrelative-backend-image
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/find-my-relative/backend:latest

